### ISSUE TITLE
Úkol 08

### ISSUE THREAD

**Issue by MagdaKra** [MagdaKra/python-kurz-2022#9]
Ahoj Moni,

 vůbec si s tím nevím rady. 

Neumím určit platnost ceny pro dané období. Tuším, že pomocí timedelta, ale nepřišla jsem na to, jak to zapsat. Nevím, jak do programu zapracovat neznámé datum, které zapíše uživatel. Pokud by to bylo nějaké konkrétní datum, asi bych ho do programu dokázala zapracovat. Jenže uživatel tam může zapsat kterékoliv datum v jakýmkoliv formátu - je tu tedy víc neznámých. Budu vděčná za nápovědu :)

Hezký den, Magda

**Comment by MonikaDvorackova** [comment]
Ahoj Magdi, 

dívám se, je tam pár chyb. Uznám ti to jako odevzdáno a jdu ti to konkrétněji napsat na Slack, doufám, že tam jsi aktivní. :)
